---
title: "Journalism"
---
<br>
Here you find a few samples of Joao Ozawa's professional experience in journalism.
<br>
<br>
<b>Globo TV</b>

Globo International is the international branch of Globo TV, a Brazilian media conglomerate and the largest TV network in Latin America. Ozawa reported on-camera as Texas correspondent for América News, a newscast that aired weekly on Globo TV International covering news of interest to the Brazilian community living in the United States. Work samples include:

• <b>COVID-19 vaccination:</b> interview with Dr. Jason McLellan, a UT professor and researcher directly involved in creating COVID-19 vaccines [[video]](https://drive.google.com/file/d/1HnILsajVcLwHBJ3lbbbwPAiyWI-IYeWp/view?usp=sharing).

• <b>COVID-19 in Texas:</b> interview with Dr. Michael Macker, director of the Center for Health Communication at UT [[video]](https://drive.google.com/file/d/1zEOtLp_LEQJUAYyMZjwzf4ueAmc32wMb/view?usp=sharing).

• <b>Mass incarceration in the U.S.:</b> interview with Preston James, CEO of DivInc [[video]](https://drive.google.com/file/d/19xIlHKnpB0O7VktQ44yFrBWlu4Wyu8di/view?usp=sharing).
<br>
<br>
<b>Estúdio Showlivre</b>

Estúdio Showlivre is a Web TV show that streams live concerts through YouTube and Facebook. Between 2015 and 2016, hosted a TV version of this online show on TV Cultura, most important public owned TV channel in Brazil. Work samples include:

• <b>Rap in Brazil:</b> In this edition of the TV version of Estúdio Showlivre, we showcased important Brazilian rap artists [[video]](https://youtu.be/SNxfysz32Es).

• <b>Akua Naru:</b> American rapper plays live at the Web TV version of Estúdio Showlivre [[video]](https://www.youtube.com/watch?v=Lf0tAwABLMQ).

• <b>Playing For Change:</b> Multimedia and global music group plays live at the Web TV version of Estúdio Showlivre [[video]](https://youtu.be/DkAFwVt4bQw?t=1228).
